<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AdvancedPlanningSystem</RootNamespace>
    <AssemblyName>AdvancedPlanningSystem</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FormMain.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FormMain.Designer.cs">
      <DependentUpon>FormMain.cs</DependentUpon>
    </Compile>
    <Compile Update="PortControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="PortControl.Designer.cs">
      <DependentUpon>PortControl.cs</DependentUpon>
    </Compile>
    <Compile Update="GlobalMonitorForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="GlobalMonitorForm.Designer.cs">
      <DependentUpon>GlobalMonitorForm.cs</DependentUpon>
    </Compile>
    <Compile Update="CassetteDetailForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CassetteDetailForm.Designer.cs">
      <DependentUpon>CassetteDetailForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FormMain.resx">
      <DependentUpon>FormMain.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Protocol.Drivers.Mitsubishi\Protocol.Drivers.Mitsubishi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PLC_Adress.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
